name: Deploy firebase web app
'on':
  push:
    branches:
      - master

jobs:
  build_web:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2
      - name: Set up .env file
        run: |
          cd ./sblweb
          touch .env
          echo REACT_APP_APIKEY=${{ secrets.REACT_APP_APIKEY }} >> .env
          echo REACT_APP_AUTHDOMAIN=${{ secrets.REACT_APP_AUTHDOMAIN }} >> .env
          echo REACT_APP_DATABASEURL=${{ secrets.REACT_APP_DATABASEURL }} >> .env
          echo REACT_APP_PROJECTID=${{ secrets.REACT_APP_PROJECTID }} >> .env
          echo REACT_APP_STORAGEBUCKET=${{ secrets.REACT_APP_STORAGEBUCKET }} >> .env
          echo REACT_APP_MESSAGINGSENDERID=${{ secrets.REACT_APP_MESSAGINGSENDERID }} >> .env
          echo REACT_APP_APPID=${{ secrets.REACT_APP_APPID }} >> .env
      - name: Build web app
        run: |
          cd ./sblweb
          npm ci
          npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web-build-artifact
          path: ./sblweb/build

  deploy_web:
    needs: build_web
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://mxm-sbl.web.app
    steps:
      - uses: actions/checkout@v2
      - name: Download web artifacts
        uses: actions/download-artifact@v2
        with:
          name: web-build-artifact
          path: ./sblweb/build
      - name: Install firebase cli tools
        run: sudo curl -sL https://firebase.tools | bash
      - name: Deploy web
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}